model:
  name: "ctc"
  hidden_size: 256
  num_layers: 4
  dropout: 0.1

trainer:
  max_epochs: 2
  accelerator: auto
  devices: auto
  log_every_n_steps: 50

training:
  batch_size: 4
  learning_rate: 0.001
  optimizer: adam
  weight_decay: 0.01
  num_workers: 4

logging:
  tensorboard_dir: "logs/tensorboard"
  local_log_file: "logs/training.log"
